"""Initial migration.

Revision ID: 8995a40dadc4
Revises: 
Create Date: 2024-07-23 14:01:19.427962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8995a40dadc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
